FORMAT: X-1A

HOST: https://oauth.brightcove.com/v3

# OAuth API v3

## The Brightcove OAuth API

The Brightcove OAuth API allows you authenticate with the Brightcove services to get access to other Brightcove APIs. For most cases, you will only use the API directly to retieve an `access_token`. For more information, see the [OAuth Overview](https://docs.brightcove.com/en/perform/oauth-api/guides/oauth-api-overview.html)

## Base URL

The base URL for the API is:

    https://oauth.brightcove.com/v3

# Group Client Credentials Flow

## Grant Credential [/client_credentials]

### POST

Operation: client_credentials_grant

+ Request
    + Headers

            Authorization: BC_TOKEN {BC_TOKEN}
            Content-Type: application/json

    + Body

            {"type":"credential",
                "maximum_scope":[
                {"identity":{
                    "type":"video-cloud-account",
                    "account-id":57838016001},
                    "operations":[
                        "video-cloud/analytics/read"]
                    }
                ],
                "name":"MyApp",
                "description":"My app"
            }

+ Response 200 (application/json)

    + Body

            {"client_secret":"f8P18FGY33piQLEx-yv7-QjFWySrjzZwkQCA2lSr6mMDspz-pQW-3Hr3xBvi-hnblOV2xqpheQPUXhm1YkBIoA",
            "issued_at":"2014-08-10T19:26:20Z",
            "name":"MyApp",
            "redirect_url":null,
            "description_html":"My App",
            "issued_to":"rcrooks@brightcove.com",
            "client_id":"ca74471c-9a1e-4afb-9ad4-19b6c52c2a21",
            "maximum_scope":[
                {"identity":{
                        "type":"video-cloud-account",
                        "account-id":57838016001},
                    "operations": ["video-cloud/analytics/read"]
                }
            ],
            "trusted":null,"type":"credential","description":"Just a test","expires_at":null,"revoked":null,"name_html":"Test2","issued_user":53255203001}

## Get Credential  [/client_credentials?origin_account_ids={VC_ACCOUNT_ID}]

### GET

Operation: list_by_pub_id

+ Parameters

    + VC_ACCOUNT_ID (required) ... Account ID List

+ Response 200 (application/json)

    + Headers

            Authorization: BC_TOKEN {BC_TOKEN}

    + Body

            {}

# Group Mange Client IDs

## Get/Delete/Update Single Client ID [/client_credentials/{CLIENT_ID}]

### GET

Operation: list_by_client_id

+ Parameters

    + CLIENT_ID (required) ... Client ID

+ Response 200 (application/json)

    + Headers

            Authorization: BC_TOKEN {BC_TOKEN}

    + Body

            {}

### DELETE

Operation: revoke

+ Parameters

    + CLIENT_ID (required) ... Client ID

+ Response 200 (application/json)

    + Headers

            Authorization: BC_TOKEN {BC_TOKEN}

    + Body

            {}

### PUT

Operation: update

+ Parameters

    + CLIENT_ID (required) ... Client ID

+ Request

    + Headers

            Authorization: BC_TOKEN {BC_TOKEN}

    + Body

            maximum_scope=[{"identity": {"type": "video-cloud-account", "account-id": {VC_ACCOUNT_ID}}, "operations": [{VC_POLICY_OPERATION}]}]
            name={VC_CC_NAME}

+ Response 200 (application/json)

    + Body

            {}
            
# Group Access Token

Gets an `access_token` that authorizes you to make calls against the API. The API and methods you are authorized for depend on the API and scope that the `client_id` and `client_secret` were granted for. Note: the `{client_id}:{client_secret}` string sent in the Authorization header must be Base64 encoded.

## Retrieve Access Token [/access_token]

### POST

Operation: access_token_grant

+ Request

    + Headers
    
            Authorization: Basic {client_id}:{client_secret}
            Content-Type: application/x-www-form-urlencoded

    + Body

            grant_type=client_credentials

+ Response 200 (application/json)

    + Body

            {
                access_token: 'abcdefg1234567',
                expires_in: 300
                token_type: 'Bearer'
            }

